### ISSUE TITLE
User Input Producer : Develop a producer node that handles the documents

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#100]
Task for #20 
The node receives the data sent by the UI through the the carriage implementation and creates a valid document from those data. The document can then be emitted to a Producer carriage Implementation

**Comment by nigelmegitt** [comment]
See also #101 - I wonder if we can generate the documents natively in the UI and just validate them in the handler/transfer node.

**Comment by gilbrechbuhler** [comment]
Document generated by the UI finally, so we remove can remove this task.
