### ISSUE TITLE
Develop a demo for the User Input Producer

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#101]
Task for #20 
Develop a demo to show the User Input Producer in action.

**Comment by nigelmegitt** [comment]
We need to come back to this from a design perspective - I think for a generalised UIP we would need to do this but it might be complex. Another option is to use a single carriage mechanism and make the UIP send XML documents directly to it, using e.g. WebSocket. That could then be picked up even on the local machine. If we want to transfer to another carriage mechanism then we'd have a consumer and producer node that does:

```
on_new_data(self, data)
    node.process_document(data)

...

TransferNode.process_document(self, data)
    outputImpl.emit_document(data)
```

In other nodes the "TransferNode" has two CarriageImpls, one for inputs and the other for outputs, which can be independent of each other.

Then in the UIP we can just have js that opens a WebSocket, creates new documents based on user input and sends them to the WebSocket; the TransferNode sends those documents on.

This is my thinking at the moment, to make the UIP as simple as possible and still have document level validation present.

**Comment by nigelmegitt** [comment]
Reviewing this issue, I think we now have enough to close this. We can currently:

1. Run `ebu-user-input-forwarder`
2. Open the `user_input_producer.html` page
3. Open in a separate window the `test.html` page
4. From the UIP page create a sequence and send documents
5. View those pages being validated in the user input producer process output
6. View the documents arriving on the test.html page

Plus we can even do this with 1x user input forwarder and _n_x sequences, generated by _n_ user input producer pages and viewed by _m_ test html pages. 

And, if we want we can show transition from one carriage mech to another by setting the user input forwarder to output to file system and then by running `ebu-simple-consumer` to show the documents' arrival being observed in the manifest file and the documents being processed.

We can also show documents being generated on demand, at scheduled times or asynchronously.

To me, this constitutes more than enough to demo the UIP!

Any other views before I close this issue?

**Comment by nigelmegitt** [comment]
One thing that would be good to do before closing this is to update the Demo bit of the documentation to include the above demo possibilities.

**Comment by gilbrechbuhler** [comment]
Will do
