### ISSUE TITLE
Set up Travis CI correctly

### ISSUE THREAD

**Issue by frans-ebu** [ebu/ebu-tt-live-toolkit#11]
- [x] make sure tests run 
- [x] trigger on pull requests only or any commit? (maybe both for now)

**Comment by nigelmegitt** [comment]
Exciting! Can we make it also rebuild documentation, or is it only able to run tests?

**Comment by frans-ebu** [comment]
@nigelmegitt I think so, it is linked to my open gh-pages action :) 
Split of into: #13
