### ISSUE TITLE
Work out the way to test sequence timing resolution

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#111]

**Comment by kozmaz87** [comment]
Framework is ready to be worked with

**Comment by nigelmegitt** [comment]
Commit ref?

**Comment by kozmaz87** [comment]
1a7ad042ff91d935cba0b66722bd21641366ee87
881f600321ed442e50b028e6db409221a17a5256
b79d9b4a2bb62353c479beb1d476046d76756714
585efc46f779a94b08ad01d5b75b0d37f4e88200
a4884d1df23ffc5b4746f3b28db63fad6bd15d08
b77bd6747c51e021a3355420cfd9009907f62335
4e0067cb8d204e7b627d24a638dee139b830eeba
1a7e211f6e310825cde69d638f7845c3661c5d11
1ae9cab7c967f209ecf4cf461146d6f207dc0f6d
3568632766aadc755113cd6ad99cd085e10383c0
b51c9d7d5ab20590c5d092d4ee9f4a01a546d9cf
18eed5d02406fbbba5d19101267329d701ffde39
a21d8f18464ebe3446ee2967f3a11dc31fc7a047
a4cec22db07b9e1ed6354c352f8698648833c100

**Comment by nigelmegitt** [comment]
Thanks
