### ISSUE TITLE
User Input Producer : Add handling of times

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#112]
Add the possibility to set :
- [x] timeBase
- [x] clockMode
- [x] dur (at body level)
- [x] begin/end (at body level for a start)
- [ ] timings for regions when #117 is done
to created documents.

For #20

**Comment by nigelmegitt** [comment]
I've split `dur` out because it's easier and can be static, and is probably more useful first than begin and end.

**Comment by gilbrechbuhler** [comment]
First two points validated in commit b0d87431c23f1f92ec1633ec25ee6a86eb305659

**Comment by gilbrechbuhler** [comment]
How much do we check user inputs on the UI side ? For the duration for example, I don't think it is a good idea to reimplement any logic concerning timing types here. I would just let the user enter whatever he wants, then show him an error when the document couldn't be validated on server side. What do you think ?

For now I just do one check : the user cannot send any document that does not have a sequence identifier.

**Comment by nigelmegitt** [comment]
I think make it lightweight at first, later you'll probably end up implementing something a bit nicer anyway. So no problem right now to leave out timing type validation.
