### ISSUE TITLE
Computed/effective begin and end times of all timed elements

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#121]
This involves the test cases submitted by Nigel on branch nigelm/test-perms.

NOTES: This should be possible by adding the parameters to the timed validation mixin and extend the timing validation function to record this information on the timed element

**Comment by nigelmegitt** [comment]
In SMIL terms the thing we're interested in is the computed _active durations_ of each element, as defined by the begin and end times, using information from the ancestors and descendants as needed. A SMIL _active duration_ is actually a period of time with a begin. The end may be defined with a value or undefined.
