### ISSUE TITLE
User Input Producer: replace \n with <tt:br/>

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#122]
Existing XML:
```xml
<tt:p xml:id="ID002">
        111
222
</tt:p>
```
Should be:
```xml
<tt:p xml:id="ID002">
      111 <tt:br/>
     222
</tt:p>
```

**Comment by nigelmegitt** [comment]
Just a regexp that replaces `\n` with `<tt:br/>` would do - you don't even need to retain the new line character.

**Comment by gilbrechbuhler** [comment]
Yes I thought about exactly the same solution, already fixing this.

**Comment by gilbrechbuhler** [comment]
Just pushed the fix if you want to try

**Comment by gilbrechbuhler** [comment]
Blank lines problem is solved, just run `make` to rebuild the template before trying.

**Comment by EyalLavi** [comment]
LGTM.
