### ISSUE TITLE
User Input Producer: null input renders as whitespace 

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#124]
If the user enters no text, this is the result:
```xml
<tt:p xml:id="ID002">

</tt:p>
```

At the minimum, this should be:
```xml
<tt:p xml:id="ID002"></tt:p>
```
(remove white space).

Even cleaner would be to remove the `<tt:body>` completely as per §3.2.1 if the document contains no text.

**Comment by nigelmegitt** [comment]
So you're seeing white space when there's none in the box? That does seem like it should be removed.

**Comment by gilbrechbuhler** [comment]
Solved in the last commit

**Comment by nigelmegitt** [comment]
That would be commit d2b504e

**Comment by EyalLavi** [comment]
LGTM, thanks.
