### ISSUE TITLE
Timing validation errors

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#125]
Tested with the UIP but may relate to XSD/validator (I haven't tested all possible combination so there may be others).

Some invalid begin/end time expressions pass validation:
- 00:11:12:_72_
- _99_:11:12 (in clock mode)

This valid time expression (`timeBase="media"`) caused a validation error but is valid:
- _99_:08:22:01

**Comment by gilbrechbuhler** [comment]
`99:08:22:01` is not valid `99:08:22.01` is however

**Comment by gilbrechbuhler** [comment]
Anyway if there is any problem with timing validation it has nothing to do in the UIP, the UIP itself checks nothing.

**Comment by gilbrechbuhler** [comment]
I confirm the problem for the first example, but this is a bigger and general issue that needs intention : we just discovered a bug in timing validation.

**Comment by nigelmegitt** [comment]
I think we should hold off on this until @kozmaz87 has finished his work on validation, then check again.

**Comment by EyalLavi** [comment]
For reference, `99:08:00` (without fraction) in `media` time base also generates validation error but is valid.

**Comment by gilbrechbuhler** [comment]
Ok, indeed that is strange, as it does not come at all from the User input producer but is more general problem, I'll rename the issue.
