### ISSUE TITLE
Set up automatic documentation building

### ISSUE THREAD

**Issue by frans-ebu** [ebu/ebu-tt-live-toolkit#13]
http://blog.gockelhut.com/2014/09/automatic-documentation-publishing-with.html

**Comment by nigelmegitt** [comment]
See also #127.

**Comment by frans-ebu** [comment]
The gh-pages integration is now set up, using a publish-key. See https://blog.ionelmc.ro/2015/07/11/publishing-to-github-pages-from-travis-ci/ for details.

Notes: 
- The travis encrypt-file command does not work well under Windows (7 at least).
- Note that Travis *will* try to build the sphinx documentation on any branch, but only push it to gh-pages if it concerns the master branch.
