### ISSUE TITLE
Refactor tests to make better use of step types

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#131]
We use "given" steps everywhere in bdd tests, however we should use "given" to give you an object and then "when" when we modify a given object.

**Comment by nigelmegitt** [comment]
Just so I understand this, is it a philosophical thing or does it lead to a practical difference in the way the tests are interpreted and used?

**Comment by gilbrechbuhler** [comment]
In practice, a `given` statement returns you an object usable and editable in all the other steps of the scenario. A `when` statement is supposed to edit an object created by a `given` statement. In practice, our tests work the same as before. However, we discovered this problem because using `given` everywhere lead to errors in the timing tests, this is how me and Zoltan discovered that using `given` everywhere was not right.

So, this is wrong
```
Given an object A
And it has A.b = 3
Then A.c() returns 4
```
And this is correct:
```
Given an object A
When it has A.b = 3
Then A.c() returns 4
```
Is correct

**Comment by nigelmegitt** [comment]
OK, thanks.
