### ISSUE TITLE
Travis seems to commit to gh-pages even if not on Master

### ISSUE THREAD

**Issue by frans-ebu** [ebu/ebu-tt-live-toolkit#137]

**Comment by frans-ebu** [comment]
This should be fixed by b38bcd4

**Comment by nigelmegitt** [comment]
Thanks Frans. That commit id looks wrong though... I think you meant 319020b ?

**Comment by frans-ebu** [comment]
yep, sorry!

**Comment by frans-ebu** [comment]
Explanation:

The conditional gh-pages commit in travis is now written in .travis.yml as:

`  - if [ $TRAVIS_BRANCH == "master" ]; then ghp-import -n -p -m "Update gh-pages." docs/build/html; fi`

However testing seemed to show a syntax that alternative syntaxes worked as well:
- "$TRAVIS_BRANCH"
- "${TRAVIS_BRANCH}"
- = (instead of ==)

The test consisted of pushing to a test branch and master and seeing if the gh-pages branch was updated. It only was on Master (as intended).

So either the yml interpreter is very liberal or something else is going on.

Note that different syntax examples can be found in several places, e.g.:
http://steven.casagrande.io/articles/travis-ci-and-if-statements/
https://github.com/travis-ci/travis-ci/issues/879
