### ISSUE TITLE
Investigate CI plug-ins

### ISSUE THREAD

**Issue by frans-ebu** [ebu/ebu-tt-live-toolkit#15]
As @kozmaz87 suggested, 2 Jenkins plug ins that would be useful:

- The junit results plugin, which makes navigation of the test suite results easy and adds retrospective of the last builds, so you can see how the test metrics changed in the last X builds

- the cobertura coverage plugin which does the same just with coverage

**Comment by nigelmegitt** [comment]
Current status:

* [x] Build test
* [x] Test coverage
* [ ] Documentation generation

**Comment by nigelmegitt** [comment]
Documentation generation is issue #13, so can we close this now?

**Comment by frans-ebu** [comment]
@nigel ok for me if @kozmaz87 agrees (as he suggested the plug ins and I don't know all detailed funtionality).

**Comment by frans-ebu** [comment]
Irrelevant as we are using Travis, now.
