### ISSUE TITLE
[EBUTTD] metadata converter

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#162]

**Comment by kozmaz87** [comment]
what is the decision on the metadata merging?

**Comment by nigelmegitt** [comment]
The decision is that it's application specific. The only part of this that I think we should implement (because we promised a while ago) is the facet -> documentFacet calculation.

**Comment by kozmaz87** [comment]
That is a different issue is it not? I mean this is only about what to do about the ebuttd merging for segmentation... for semantic validation of part3 and facet calculation another ticket should be created

**Comment by nigelmegitt** [comment]
oh sorry right, yes, for just ebuttd we don't really have to to anything: dropping all the metadata is probably the best thing to do. Some folk might get sniffy about dropping the ttm:copyright though! We possibly should keep that in if we can...

**Comment by kozmaz87** [comment]
lifted out to #278
