### ISSUE TITLE
[EBUTTD] create conversion classes

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#170]
Subtasks:
- [ ] tt converter #169
- [x] body converter #168
- [x] head converter #167

Relevant conversation:

nigel [4:46 PM]  
somewhere you also need to make a decision about whether to put timings on `span` or `p` (you can’t have them on both in EBU-TT-D). Obviously you have the timings, so I guess if all the children of a p have the same timing then float the timings to the p, otherwise put them all on every span.

**Comment by nigelmegitt** [comment]
Considering pushing this back to a later release since EBU-TT-D encoding is good enough for now.

**Comment by nigelmegitt** [comment]
#169 has been pushed to R3, closing this with that part not done, for R2.
