### ISSUE TITLE
[EBUTTD] Style and region linking for subset

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#171]
Relevant conversation:

nigel [4:48 PM]  
It’s a mapping exercise. TT3 doc 5 had `div region="r1"` and doc6 has the same but the region definitions are different.

[4:49]  
Then when you create the region corresponding to the content from doc 5 you create a map entry “I need a region for doc 5 r1”, use an ID generator to give you a new unique id value U1, and record the mapping from doc 5 r1 to U1. Then when you get to doc 6 r1 you find you don’t have an entry in the map, so you make one, and get U2 for it.

[4:50]  
The later optimisation is to identify identical regions and combine them.

[4:50]  
the map could be done with clever IDs but it’s not lovely. e.g. create a new unique id by concatenating sequenceId + sequenceNum + xml:id

**Comment by kozmaz87** [comment]
NOTE: contents of tt/head/layout are optional and layout itself is optional as well. Maybe on purpose maybe just bit too loose. unsure.

**Comment by nigelmegitt** [comment]
Not sure what impact this note has? It's deliberate in the EBU-TT Part 3 spec to leave them optional, but it's equally deliberate in EBU-TT-D to require them to be present except in the "empty document".
