### ISSUE TITLE
[EBUTTD] Add EBU-TT-D XSD 1.0 to repository and update it if necessary

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#177]
https://github.com/ebu/ebu-tt-d-xsd

As much as we could tell there are some transformations we should apply. Such as convert root elements to types.

**Comment by kozmaz87** [comment]
Issues found with xsd so far:
Mismatches between live(ours) ebuttd(theirs) XSDs:
  * mismatch in cellresolutiontype (ours allows leading zeros, theirs does not)

**Comment by tairt** [comment]
I think your regular expression (`[0]*[1-9][0-9]*\s[0]*[1-9][0-9]*`) to restrict the type of cellResolution is a more accurate representation of the spec constraint. Can you open issue at https://github.com/ebu/ebu-tt-d-xsd? We can then fix the issue in the EBU-TT-D XSD.

**Comment by kozmaz87** [comment]
https://github.com/ebu/ebu-tt-d-xsd/issues/7
