### ISSUE TITLE
Test R8 R37

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#185]
Each document in a sequence shall have a distinct sequence number.

**Comment by nigelmegitt** [comment]
Just been reviewing #182 and looking at the requirements list, and R8 and R37 seem to have nothing to do with sequence numbers. I'm a bit confused by this. Also there has been spec change work that modifies some of the requirements. Will raise that separately.

**Comment by nigelmegitt** [comment]
The new spec text here says that if a document is received with a sequence id + number pair that has already been received then the later one shall be discarded. No document equality test is needed any longer.

Reassigning to @EyalLavi to update the conformance requirements list please and then update this issue. It could be we just need to close this issue and the associated pull request. By the way, when updating the conformance requirements please do not reuse any R numbers, but mark no-longer-relevant ones as "unused" or "deprecated" or something and add new numbers for different requirements.

**Comment by EyalLavi** [comment]
I've marked R8 and R37 as deprecated since we are no longer comparing the content of documents to determine if they are distinct. Instead, new R107 was added: 

> Processors shall discard documents whose pair of `ebuttp:sequenceIdentifier` and `ebuttp:sequenceNumber` are identical to those in a previously received document. The availability time of the document shall not be changed due to such a discard.

I've opened #297 for this requirement.
