### ISSUE TITLE
COMPONENT: User input producer

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#20]
As a developer/tester, I want a sequence of part 3 documents generated from text input so that I can develop/test an implementation against it.

Input: Text file provided by user.
Output: Sequence of EBU-TT Live documents.

**Comment by gilbrechbuhler** [comment]
Here is a first breakdown of this issue to tasks :

- [ ] Define precisely what functionalities are expected from this component
- [ ] Define and develop a simple UI able to send documents to a carriage implementation (depending of the functionalities expected from the UI this will be broken in sub-tasks)
- [ ] Develop a carriage implementation able to parse the data sent by the UI
- [ ] Develop a producer able to emit a document from the data received from the carriage implementation
- [ ] Demo :
 - [ ] Connect the producer to a Producer Carriage Impl. to be able to send the created document to a consumer node
 - [ ] Write a script making it all work together so the user can type text and the final document is outputed in the consumer node.

**Comment by nigelmegitt** [comment]
Thanks Gil, I've sorted those into a rough priority order.

**Comment by nigelmegitt** [comment]
We have enough now on this to close it for R2 - @gilbrechbuhler or @EyalLavi please could you create a new issue for UIP enhancements and move all the not-yet-done subtasks from here to the new issue, so we can close this off and not lose anything?

**Comment by EyalLavi** [comment]
Sure I'll do it.

**Comment by EyalLavi** [comment]
Issue #180 created for the remaining tasks so I'm closing this one.
