### ISSUE TITLE
FilesystemConsumerImpl swallows exceptions

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#214]
This is a bug:

```
    try:
        document = EBUTT3Document.create_from_raw_binding(CreateFromDocument(xml_content))
    except:
        log.exception(ERR_DECODING_XML_FAILED)
        raise XMLParsingFailed(ERR_DECODING_XML_FAILED)
```

**Comment by kozmaz87** [comment]
There is a question about this one. Which errors do we want to break the system and which errors should be ignored.

**Comment by kozmaz87** [comment]
Another very interesting question: The whole error check was there becasue the filesystem carriage kept processing the documents into the validator and parser and assigned their availability times. This should not be required any longer. So we can simplify the filesystem carriage and pass on availability_time as a keyword argument. If the node that the carriage is connected to wants EBUTT3Document, then automatic conversion happens and that will look for the availability_time flag in the passed keyword arguments.

**Comment by kozmaz87** [comment]
related to #284

**Comment by nigelmegitt** [comment]
OK that sounds like a good improvement. I think the point of the original bug was simply that the way the error is caught loses the detail, so it was not possible to see the stack trace or whatever.

**Comment by nigelmegitt** [comment]
Closing as fixed.
