### ISSUE TITLE
ebu-dummy-encoder: Missing extent

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-live-toolkit#237]
The `ebu-dummy-encoder` is not able to produce a valid EBU-TT output and instead returns a traceback. The reason is that the defined style uses a `fontSize` of `12px`, but no `extent` is specified on the root `tt` element.

**Comment by kozmaz87** [comment]
This issue is fixed on the kozmaz87/segmentation branch and will be merged as part of that.

**Comment by spoeschel** [comment]
Ah, thx!
