### ISSUE TITLE
Timed containers do not inherit computed begin time from children

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#238]
This applies in the case when the timing container does not specify a timing of its own. In this case the computed begin time will be 00:00:00 or whatever is inherited from the parent element or availability time.

**Comment by kozmaz87** [comment]
This behaviour however intuitive it may seem contradicts 2.3.1(R16)

**Comment by nigelmegitt** [comment]
I see, yes, you mean §2.3.1.1 specifically, right? However, note that there is a difference between the begin time of an element and the earliest begin time of a document. Not sure if that has a bearing here though.
