### ISSUE TITLE
False timeline inconsistency detected

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#248]
When a document exactly overrides a previous version of itself in the very unlikely but not impossible scenario of both of them being available at the same time.

**Comment by nigelmegitt** [comment]
You mean when two documents have identical content and timing but different sequence numbers, and both of their availability times are in the past?

**Comment by kozmaz87** [comment]
their content is different since it is an update.

**Comment by kozmaz87** [comment]
I believe however that my fix is broadening out this check too much and it might let something slip away...

**Comment by kozmaz87** [comment]
This says in English the following: If there are 2 different documents: one of them begins before our current insertable document and the other one ends after our current document began then the second one has no begin time
