### ISSUE TITLE
[Consumer] Do not accept the same sequence number twice

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#258]
Also produce a warning message if the document content would otherwise be different from the one we already have in the sequence object.

**Comment by nigelmegitt** [comment]
I would make this very simple - generate a hash of the raw string of the XML document and compare this to the hash of the previously received document with the same sequence id and number - if the hashes differ then issue the warning message. No need to do in-depth comparison of documents.

The only reason against this that I am aware of is if we want to exclude any debug trace/appliedProcessing metadata from the comparison.

**Comment by EyalLavi** [comment]
The warning message part of this issue was extracted into issue #335
