### ISSUE TITLE
Documentation on structure of repository

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#260]
Navigating the source code seems to be difficult for new people. Documentation is needed or restructuring based on their input.

**Comment by nigelmegitt** [comment]
Assigning to @kozmaz87 and also @malikbeytrison for @malikbeytrison to provide some notes on his experiences, as discussed in this morning's standup.

**Comment by kozmaz87** [comment]
hm wondering about this ticket

**Comment by nigelmegitt** [comment]
Here's @malikbeytrison 's feedback, so it doesn't get lost (hope you don't mind me copying from a private slack channel to here @malikbeytrison !):

>* Timing: I think it's for me the most difficult aspect I had to go through. It is difficult to understand what are all these different times (resolved, computed, availability, begin, end, dur). 
>* Flow of things: how are things started, who talks to who. It's not obvious at first glance. This picture http://ebu.github.io/ebu-tt-live-toolkit/html/nodes_and_carriage_mechanisms.html shows the different components but not really how they are linked together. A diagram of visual representation of step-by-step operations would be nice to have.
>* Twisted: still not sure how it works
>* Tests: not sure if it's me lacking of knowledge in this area, but maybe some details would be nice here

I think that the pictures @kozmaz87 sketched up in the face to face meeting helped, as well as the newly introduced little code map describing the directory structure at http://ebu.github.io/ebu-tt-live-toolkit/html/ebu_tt_live.html#layout-of-the-source-files .

Maybe those UML class diagrams converted to sphinx are a good place to start.

**Comment by nigelmegitt** [comment]
By the way there is also #178 which is related.

**Comment by nigelmegitt** [comment]
I feel this is good enough for now - some changes were made as part of release 2 including a lot of documentation and diagrams, so I'm closing this for now and new issues can be added if there is further feedback requesting more documentation.
