### ISSUE TITLE
[DELAY NODE] implicit->explicit conversion seems to be necessary for good results

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#265]

**Comment by nigelmegitt** [comment]
I don't agree it is necessary, but it can be helpful in some circumstances.

**Comment by EyalLavi** [comment]
This is superseded by the decision in the F2F 2016-11-24 to split delay node into 'Buffer delay node' and 'Retiming delay node'. Zero offset in retiming node stamps explicit times on implicitly timed documents. See https://git.ebu.io/ebutt/ebutt-part-3/issues/130
