### ISSUE TITLE
[TESTING] EBUTTDEncoder node needs cleanup and testing

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#268]

**Comment by nigelmegitt** [comment]
We need more detail on this to be able to assess it. @kozmaz87 can you please elaborate?

**Comment by nigelmegitt** [comment]
Assigning to @kozmaz87 because this is a question for him.

**Comment by nigelmegitt** [comment]
Fixed by #361.
