### ISSUE TITLE
[WEBSOCKET] Switch to a URI scheme instead of inband channel requests

### ISSUE THREAD

**Issue by nigelmegitt** [ebu/ebu-tt-live-toolkit#279]
We currently offer generic WebSockets and send some non-specified data to request a "channel" corresponding to a sequence id. And we are a bit vague about whether we expect to receive data from or send data to a node.

Change this to use the following URI pattern:

`[ws|wss]://[host]:[port]/[sequenceId]/[publish|subscribe]`

Where a `/publish` connection means "I'm going to send you this sequence" and a `/subscribe` connection means "please send me this sequence".

**Comment by kozmaz87** [comment]
related to: #288

**Comment by nigelmegitt** [comment]
This was done as part of the merge of configurator and #288.
