### ISSUE TITLE
COMPONENT: Distributor node

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#29]
As a playout service provider, I want to distribute a sequence so that it can be processed by multiple consumers.

Input: a sequence of part 3 documents
Output: a sequence of part 3 documents available to multiple destinations

**Comment by nigelmegitt** [comment]
This is effectively already done with the user input forwarder.

**Comment by kozmaz87** [comment]
I think we should close it then

**Comment by nigelmegitt** [comment]
User Input Forwarder is one case of this that accepts an incoming "publish" connection and also outgoing "subscribe" connections, but in general it should be able to make outgoing subscribe connections too, and outgoing publish connections, to be generally useful.

**Comment by kozmaz87** [comment]
Latest update on this is that the DistributingNode class implements a very simple pass-on principle whatever comes in and survives validation will be immediately passed to the output. The distribution capability however does not rest with the Node, but the carriage mechanism. It comes down to the concept of a 'client' or 'destination'. In different carriage mechanisms client/destination may not mean the same thing.

There is also a new ticket: #332 to identify use-cases for this node and create testing and also example runtime configurations for them

**Comment by nigelmegitt** [comment]
Please can you reference the code with the DistributingNode class as a commit or preferably a pull request @kozmaz87 ?

I do not think the component requires the functionality specifically to be in a Node object; the implementation approach you suggest seems like exactly what we need, to me.

In terms of #332 and use cases I have added an entry. I do not think we need to get too bogged down in all the possibilities now - we can simply create a test that multiple incoming sequences are distributed to multiple outgoing nodes. An example runtime configuration would be:

```
node1:
   distributing node
node2:
   consumer node, makes outgoing /subscribe connection to distributing node sequence_id_1
node3:
   consumer node, makes outgoing /subscribe connection to distributing node sequence_id_2

UIP connects to distributing node with sequence_id_1 with intent to publish; sends document. node2 receives it, node3 does not.
A second UIP connects to distributing node with sequence_id_2 with intent to publish; sends document. node2 does not receive it, node3 does.
A third UIP connects to distributing node with sequence_id_3 with intent to publish; sends document. neither node2 nor node3 receives it.
A fourth UIP connects to distributing node with sequence_id_1 with intent to publish; sends document. node2 receives it, node3 does not. Processing depends on sequence number, if it should be discarded etc.
```

**Comment by nigelmegitt** [comment]
I've just checked and `config/node.py` has `nodes_by_type` and none of them is a distributor. So this does not yet appear to be possible. Looks like it needs to be wired into the node configuration.
