### ISSUE TITLE
FilesystemCarriage tests need updating

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#290]
#285 surfaced that there were way too many assumptions in those tests and now that the interface contract is tighter it starts to surface.

**Comment by kozmaz87** [comment]
Skipped some in 93b711a

**Comment by nigelmegitt** [comment]
We need some details here - I cannot assess this because the assumptions are not written down anywhere I can see them.

**Comment by kozmaz87** [comment]
yes this is basically that the carriage mechanism grabs over to simple consumer to grab the clock and ask about availability and whatnot. but I will have to detail this I guess

**Comment by nigelmegitt** [comment]
@kozmaz87 is this in your latest batch of fixes?

**Comment by kozmaz87** [comment]
No
I did fix these later on the R2fixes branch I reckon

**Comment by nigelmegitt** [comment]
Thank you - when the pull request is opened for that we can mark this as pending pr merge then.

**Comment by nigelmegitt** [comment]
This has been merged. Closing.
