### ISSUE TITLE
[DELAY NODE] BDD tests for BufferDelayNode

### ISSUE THREAD

**Issue by malikbeytrison** [ebu/ebu-tt-live-toolkit#293]
Approach: 

Producer Node -> [1. Consumer Node A that logs resolved document begin time; 2. BufferDelay Node -> Consumer Node B]. Difference between resolved document begin times logged by A and B should be equal to delay period.

**Comment by nigelmegitt** [comment]
I've just realised that the test for passive nodes (as the Buffer Delay Node is) not modifying documents is partially implemented already in #202, which is not yet merged. There may be something we can reuse there...
