### ISSUE TITLE
[Websocket] - implement limited number of connections

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#307]
The kind of node that is pulling in the carriage mechanism tells how many clients it is willing to accept. It is the carriage mechanism's responsibility to facilitate uni or multicast. The websocket implementation does it differently than for instance UDP or direct.

**Comment by nigelmegitt** [comment]
This is a contract between the node and the carriage mech - the node can not demand multiple clients if the carriage mech cannot facilitate it, but the node should be able to request limited clients if the carriage mech has a choice.

**Comment by nigelmegitt** [comment]
We don't seem to need this immediately, pushing back to R3.
