### ISSUE TITLE
[Websocket] Escape sequenceIdentifier when using in a URL

### ISSUE THREAD

**Issue by nigelmegitt** [ebu/ebu-tt-live-toolkit#308]
Since `ebuttp:sequenceIdentifier` is an `xs:string` it can contain characters that need to be escaped in URLs. Escape this path segment and de-escape it as needed.

Possibly helpful documentation at https://twistedmatrix.com/documents/16.3.1/api/twisted.python.url.URL.html for doing this in twisted.

**Comment by nigelmegitt** [comment]
@kozmaz87 is this actually done? There's no PR referencing the issue but I think we did implement it...

**Comment by kozmaz87** [comment]
7e637b6  - f904d97 commits add in the unittesting capability and the functionality. The rest are preparation for the full system testing of the same feature.

**Comment by nigelmegitt** [comment]
This is close enough for now, we should have a different issue to complete the WebSocket BDD testing if we need to do that.
