### ISSUE TITLE
Update UIP documentation

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#310]
Keyboard shortcuts have been added for the demo. If these make it to master, update the documentation for the User Input Producer. 
- Space and enter send the document but the actual characters are not included in the sent document (e.g. space appears with the following word)
- Escape sends the document and clears the text.

**Comment by nigelmegitt** [comment]
Also, 32b6cf00626a36acfb555135287928af01c03a85 introduced:

* a maximum number of lines control: on pressing Enter the current text area is sent, and the number of lines is reduced by removing the first _n_ as needed so that on next pressing Enter the maximum desired number of lines will be sent.

**Comment by nigelmegitt** [comment]
Marking as R2 since there's an open pull request to make these changes on master, for #313 which is now also marked as R2.

**Comment by nigelmegitt** [comment]
This should be considered a subtask of #323.
