### ISSUE TITLE
UIP bug: 'Send document' options not displaying in Safari

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#321]
Steps to reproduce: 

1. Open `user_input_producer.html`
2. Select 'On schedules time' or 'asynchronously'
3. The corresponding options do not appear.

Applies to Safari. Tested okay in Chrome and FF on OSX.

**Comment by EyalLavi** [comment]
This seems to be known issue so I'm hoping to fix it for a minor release: https://stackoverflow.com/questions/32147478/safari-error-syntax-error-unrecognized-expression-inputdata-card-type-pay

**Comment by EyalLavi** [comment]
This should have been closed automatically when the PR was merged, not sure why it hasn't. Anyway, closing.

**Comment by nigelmegitt** [comment]
No, you've forgotten we close the issues when we release. This is merged into release/2.1.1 only.
