### ISSUE TITLE
[ReSequencer] begin_output implementation

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#328]
Implement a setting for resequencer to time when its first segment is supposed to be produced according to the input clock

**Comment by kozmaz87** [comment]
immediate | "clock_time"

**Comment by nigelmegitt** [comment]
This is a duplicate of #329 - closing this one as a duplicate because there's a bit more detail in the other one. Sorry @kozmaz87 - and you got there first too!
