### ISSUE TITLE
"Pre-generate" documentation on web space

### ISSUE THREAD

**Issue by tairt** [ebu/ebu-tt-live-toolkit#334]
It would be super helpful if the documentation could be pre-generated and hosted on any web space (e.g. using gh-pages possibly using a separate branch). Without building the project you could review the features/API's that are supported. It may not be straightforward to generate the documentation in every system environment yourself.

**Comment by nigelmegitt** [comment]
This is already done - click on Documentation at http://ebu.github.io/ebu-tt-live-toolkit/ to go to the pre-built documentation based on what is in the master branch.
