### ISSUE TITLE
Deprecate R115

### ISSUE THREAD

**Issue by nigelmegitt** [ebu/ebu-tt-live-toolkit#352]
In anticipation of widespread joy at me removing the spec requirement R115, we should strike it out from `spec-conformance.md`.

**Comment by EyalLavi** [comment]
I've created a branch and deprecated the requirement from SPEC-CONFORMANCE.md but the corresponding BDD is not in this branch so I'll wait until the other one is merged to remove it.

**Comment by kozmaz87** [comment]
It was merged earlier today right?

**Comment by nigelmegitt** [comment]
Yes but not yet reviewed by the group.

**Comment by nigelmegitt** [comment]
This has been done and merged. Closing the issue.
