### ISSUE TITLE
[Handover] - Create configurator

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#368]
The config options so far:

  - sequence_identifier
  - authors_group_identifier

**Comment by nigelmegitt** [comment]
This appears to be in release/2.1 already, not sure which PR brought it in...

**Comment by EyalLavi** [comment]
Seems to have been fixed in ebu/ebu-tt-live-toolkit@fecc259#diff-ce6de0c993ce80e61b9e2a7923d7e909. I'm applying the label for sorting but it's already merged.

**Comment by nigelmegitt** [comment]
If I am using the GitHub UI correctly this is merged into `release/2.1` but not `master` yet, so this is correctly labelled and milestoned already.
