### ISSUE TITLE
COMPONENT: WebSocket carrier

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#37]
As a playout service provider, I want to carry EBU-TT Live documents using the WebSocket protocol so that I can use EBU-TT Live over TCP.

Input: a sequence of part 3 documents.
Output: a sequence of part 3 documents for RFC 6455.

**Comment by nigelmegitt** [comment]
Note that basic WebSocket carriage was implemented in Release 1.

**Comment by nigelmegitt** [comment]
This is implemented awaiting merge of pull request #295.

**Comment by nigelmegitt** [comment]
#295 merged, closing.
