### ISSUE TITLE
Update README for ebu-run script

### ISSUE THREAD

**Issue by nigelmegitt** [ebu/ebu-tt-live-toolkit#371]
Maybe point to built documentation for config etc rather than listing scripts.

**Comment by EyalLavi** [comment]
@nigelmegitt not sure I understand. Did you mean 'create a README for scripts folder'?

**Comment by nigelmegitt** [comment]
No, `README.md` in the top level refers to the scripts but it should be updated to mention `ebu-run` and the example scripts in `examples/config`.
