### ISSUE TITLE
[Handover] - Unittest handover node

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#373]
This does not have to reproduce the business case that is in the BDD already. This one needs to check that the implementation details are correct.(the correct parameters are set...etc)

**Comment by EyalLavi** [comment]
Appears to have been fixed in https://github.com/ebu/ebu-tt-live-toolkit/commit/fecc259ac6046989ef287497cfe9d5b90a04e93d#diff-ce6de0c993ce80e61b9e2a7923d7e909
