### ISSUE TITLE
[Handover, UIP] - Modify UIP to support the handover workflow better

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#374]
This includes a subscribe feature and a side panel where the current documents are running. To be concluded the source. 
Hint: authorsGroupControlRequest gets discarded on handover output... :S

Subtasks: 

  - [x] #379
  - [x] #380
  - [x] #381

**Comment by nigelmegitt** [comment]
The subtasks are all now pending PR merge into master.
