### ISSUE TITLE
Test referenceClockIdentifier validation

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#38]
Allows the reference clock source to be identified. Permitted only when
ttp:timeBase="clock" AND ttp:clockMode="local" OR when
ttp:timeBase="smpte".

**Comment by gilbrechbuhler** [comment]
The PR is ready, I'm just waiting for my #18 to be merged in order to avoid conflicts (did some corrections in #18 )

**Comment by gilbrechbuhler** [comment]
Branch is referenceClockIdentifier_validation_tests

**Comment by nigelmegitt** [comment]
PR #55 now merged - closing.
