### ISSUE TITLE
[UIP] Add visual indication when sequence is currently selected

### ISSUE THREAD

**Issue by nigelmegitt** [ebu/ebu-tt-live-toolkit#382]
Add a visual indication ("On air" or something similar) to show when the most recent document output from the handover manager came from this sequence. Show a different indication when the most recent document did not come from this sequence ("Standby").

When not selected, add a visual indication ("Will take over") to show when a document submitted with the current control token _would_ be selected, i.e. it is greater than the most recently received control token.

**Comment by kozmaz87** [comment]
How does the UIP know? the identifiers are replaced. Heuristical approach is not 100%(comparison of xml content/authorsGroupControlToken) for such a feature to work you need some normative compulsory identifier in the document

**Comment by nigelmegitt** [comment]
The authorsGroupIdentifier is the same on the output of the Handover Manager as the input so that should suffice.

I would base this on the Handover Manager (our implementation) outputting the control token from the selected input sequence in its output. That's not a requirement but a permitted option. Good for showing one way it could work.

**Comment by kozmaz87** [comment]
the authorsGroupIdentifier does not identify the source.

**Comment by nigelmegitt** [comment]
Oh wait I see, sorry, you're saying that you may get a document in the Handover Manager's output sequence that _looks_ like the document most recently sent but you cannot tell if it is actually the same or a coincidence.

The identifier I would use here is `ebuttm:documentEditorsName` on the assumption that each editor is uniquely named. I don't think we have anything stronger than this, unless we want to add some source metadata in an `ebuttm:appliedProcessing` message, which is also possible.

**Comment by nigelmegitt** [comment]
OK then one option is to craft an `ebuttm:appliedProcessing` element with that data in it. It is fine to make this an implementation-specific behaviour and for it not to be a specification requirement, I think. 

The other option is to make an attribute on the document, say `ebuttm:authorsGroupSelectedSequenceIdentifier` that would be placed on `tt/head/metadata`. That could be added to the metadata spec, I think there is just enough time if we are quick...

**Comment by kozmaz87** [comment]
I definitely like the second option. Crazy long name but conveys what it is. Can I go forward and implement this option when I get to this?

**Comment by nigelmegitt** [comment]
In principle yes, however I'm unsure about if we can get this in the spec in time. It would be a late addition to the Metadata spec. We can raise that as an issue now I suppose.

**Comment by kozmaz87** [comment]
So what are we to do about this ticket in the meantime?

**Comment by nigelmegitt** [comment]
Proceed please.

**Comment by nigelmegitt** [comment]
For completeness I should say I briefly considered using a new message type for indicating that a sequence has been selected but that would definitely not be synchronous with the message and if the message gets missed for whatever reason then the node looking for this information would never find it.
