### ISSUE TITLE
Fix SPEC-CONFORMANCE.md formatting

### ISSUE THREAD

**Issue by nigelmegitt** [ebu/ebu-tt-live-toolkit#388]
Something has happened to the presentation of `testing/SPEC-CONFORMANCE.md` that breaks the table layout, it needs to be fixed :-( This could be a GitHub change, I'm not sure. It's a bit nasty though!

**Comment by EyalLavi** [comment]
My changes don's seem to take effect so I submitted a ticket to Github.

**Comment by nigelmegitt** [comment]
Did GitHub provide a ticket number? (I don't think they do, just checking)

**Comment by EyalLavi** [comment]
They don't. My email address is the only reference.
