### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SKHameed86** [ebu/ebu-tt-live-toolkit#404]
There's a typo on line `53:100` of the `...bindings/validation/timing.py`

**Comment by nigelmegitt** [comment]
I think you mean the line:

```python
        self._semantic_dataset['timing_end_limit'] = max(self._semantic_dataset.get('timing_end_limt', timedelta()), proposed_end)
```

- is it the apparently missing 'i' in `timing_end_limt`? What is the impact of that typo?

**Comment by kozmaz87** [comment]
From the looks of it there must be an impact as the max will always end up selecting whatever proposed_end is or timedelta(), which is 0. But never timing_end_limit as it is looking for timing_end_limt, which is wrong... this is basically failing to update the `timing_end_limit` with the right value.... I will think of a case to expose the error this creates. There must be a problem with out testing missing a case this line does cater for. I will have to switch my timing resolution mind back on....
