### ISSUE TITLE
ebu-simple-producer 'filesystem' error

### ISSUE THREAD

**Issue by SKHameed86** [ebu/ebu-tt-live-toolkit#407]
When creating subtitles to be output using the filesystem carriage, the code I am using is: `ebu-simple-producer --folder-export export`, and the error is: `TypeError: __init__() takes exactly 2 arguments (3 given)`

**Comment by EyalLavi** [comment]
@SKHameed86 is this related to #409? If so, is it fixed?

**Comment by SKHameed86** [comment]
This seems to be unrelated to https://github.com/ebu/ebu-tt-live-toolkit/issues/409 and has not been resolved.

**Comment by EyalLavi** [comment]
Summarising chat with @SKHameed86: this issue might be related to using the legacy standalone script. @SKHameed86 will try with `ebu-run` and a filesystem configuration file to test this theory.

**Comment by SKHameed86** [comment]
`ebu-run` with the filesystem configuration works.

**Comment by EyalLavi** [comment]
Closing this issue but the standalone script should be clearly indicated as deprecated in #443.
