### ISSUE TITLE
ebu-simple-consumer 'filesystem' error

### ISSUE THREAD

**Issue by SKHameed86** [ebu/ebu-tt-live-toolkit#408]
When using the consumer to take in created subtitle files and output them into a single file using the filesystem carriage, the code I am using is: `ebu-simple-consumer --manifest-path export/manifest_TestSequence1.txt` and the error I am receiving is: `TypeError: object() takes no parameters`

**Comment by EyalLavi** [comment]
@SKHameed86 is this related to #407? If so, was it fixed in https://github.com/ebu/ebu-tt-live-toolkit/commit/2a305b842ceea9257fa77101a0baf5fba34dd30c?

**Comment by SKHameed86** [comment]
This seems to be unrelated to https://github.com/ebu/ebu-tt-live-toolkit/issues/409 and has not been resolved.

**Comment by EyalLavi** [comment]
Summarising chat with @SKHameed86: this issue might be related to using the legacy standalone script. @SKHameed86 will try with `ebu-run` and a filesystem configuration file to test this theory.

**Comment by SKHameed86** [comment]
`ebu-run` with the filesystem configuration works.

**Comment by EyalLavi** [comment]
This is good news. We've removed references to the standalone scripts from the documentation but they are still in the repo so we should add a comment in the code to say that they are deprecated. I've opened issue #443 for this.
