### ISSUE TITLE
Slack notifications granularity

### ISSUE THREAD

**Issue by frans-ebu** [ebu/ebu-tt-live-toolkit#41]
Check if we all agree with changing the notifications to only show:

- Failures 
- Changes (includes the first build after fails)

Responses:
- [x] Frans OK
- [x] Zoltan OK
- [ ] Eyal
- [ ] Nigel
- [x] Gil

**Comment by nigelmegitt** [comment]
Do the notifications apply across all branches or just the master branch?

**Comment by frans-ebu** [comment]
@nigelmegitt 
Any branch that has a .travis.yml file

**Comment by nigelmegitt** [comment]
I don't agree. I think we should use the Travis defaults for the Slack channel (notify on everything) and we should set Slack up to notify us based on our username if we only want to see our own builds - that's an individual setting. The email notifications are also standard, to notify when a build becomes broken or goes from broken to fixed. I'm happy with both the Travis defaults.

**Comment by frans-ebu** [comment]
I agree, Travis defaults make sense :)
