### ISSUE TITLE
Unit-Test documents comparison (ComparableMixin)

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#43]
Documents use the mixin ComparableMixin (defined in the project root in file utils.py). This mixin allows for correct and easy comparison of documents :

- two documents with the same sequenceIdentifier will be compared using their sequenceNumber : 
```
document1 < document2 if document1.sequenceNumber < document2.sequenceNumber
```

- If the documents do not have the same sequenceIdentifier, there is no comparison possible and an error is raised.

With this issue I want to address the fact that this was not tested yet, so I implemented tests to ensure that document comparison works as intended.

**Comment by nigelmegitt** [comment]
Sorry, I'm not following what the issue is here - please could you add a description?

**Comment by gilbrechbuhler** [comment]
Documents use the mixin ComaparableMixin (defined in the project root in file utils.py). This mixins allows for correct and easy comparison of documents :

- two documents with the same sequenceIdentifier will be compared using their sequenceNumber : 
```
document1 < document2 if document1.sequenceNumber < document2.sequenceNumber
```

- If the documents do not have the same sequence number, there is no comparison possible and an error is raised.

With this issue I want to address the fact that this was not tested yet, so I implemented tests to ensure that document comparison works as intended.

Sorry, I forgot to put a description.

**Comment by nigelmegitt** [comment]
Thanks, that's clear!

**Comment by gilbrechbuhler** [comment]
I think we can close this one as the corresponding PR ( #44 ) as been merged.
