### ISSUE TITLE
Replace references to standalone scripts

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#433]
The documentation contains instructions for starting nodes directly (e.g. `ebu-user-input-consumer`). This method has been deprecated and `ebu-run` should be used instead.

**Comment by nigelmegitt** [comment]
This should include #371 but also applies to the documentation as well as the README.

**Comment by nigelmegitt** [comment]
I've merged the other branches that made documentation changes, so this is the only one that still needs doing I think.
