### ISSUE TITLE
Error when parsing XML ebuttm:documentStartOfProgramme

### ISSUE THREAD

**Issue by danielthepope** [ebu/ebu-tt-live-toolkit#492]
I am trying to parse an EBU-TT-Live document using `EBUTT3Document.create_from_xml(xml)`. The `xml` variable is a string read in from a file.

The XML contains the following in the `<ebuttm:documentMetadata>` block:
```
<ebuttm:documentStartOfProgramme>10:00:00:00</ebuttm:documentStartOfProgramme>
```

However I'm getting a KeyError in `ebu_tt_live/bindings/_ebuttdt.py:73`: No such key `timing_attribute_name` in the XML parsing context.

**Comment by nigelmegitt** [comment]
Thanks @danielthepope great issue! I can see that there are two problems (at least):

1. The XSD doesn't match the Tech3390 spec for that element type, which allows either `ebuttdt:smpteTimingType` _or_ `ebuttdt:clockTimingType`.
2. The code has a mix-in for conversion/semantic validation of time expressions that both a) seems to assume that time expressions are always in attributes (which in this case is untrue - it is in an element) and b) runs despite no particular validation or conversion really being needed.
