### ISSUE TITLE
File system carriage mechanism

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#50]
Refers to [BBC's fork issue 18](https://github.com/bbc/ebu-tt-live-toolkit/issues/18)

This issue asks for the implementation of a functionality that allows the simple producer to write its output to the file system along with a manifest file with availability times.

**Comment by nigelmegitt** [comment]
This is effectively a 'file system' based carriage mechanism. Will be very useful for testing and debugging processes if nothing else.

**Comment by gilbrechbuhler** [comment]
Thank you for pointing the misnaming here, corrected.

**Comment by gilbrechbuhler** [comment]
Ok, the local clock used by the SimpleProducer is a local clock which has :

```
def get_time(self):
        now = datetime.now().time()
        return timedelta(hours=now.hour, minutes=now.minute, seconds=now.second, microseconds=now.microsecond)
```

Which means that we never get the date included. And I use the producer's clock to get "available times". However, @frans-ebu pointed out that question : "how do we handle the case when we have a manifest file that spans over two days if we do not have dates ?".

I ask this question here because we have to use the node's clock to make sure the "availability" times are coherent with the times in the produced document.

**Comment by nigelmegitt** [comment]
We need to put times in the manifest file that can be compared with document times, so we should either put the availability times in the same timeBase as the documents, or provide some kind of offset value to show how to relate the manifest times with the document times. Agreed during call of 2016-07-13 to use the same timeBase because it's simpler.

**Comment by gilbrechbuhler** [comment]
As currently the code that writes the manifest file uses the producer's clock, it is already the case. I need to see if it works well with a media clock.

**Comment by gilbrechbuhler** [comment]
Let's break down what is left to do :

- [ ] Add the availability time as an attribute of `EBUTT3Document` class
- [ ] Write a consumer node able to produce a text output simulating the documents and there activation times
