### ISSUE TITLE
Resequencer: document w/o content always has sequence number 1

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-live-toolkit#502]
When the Resequencer is used, it may happen that in the meantime no new Part 3 segments are queued and hence the regular output document is a document without content (which is a special case in the code). However this empty document always has a `ebuttp:sequenceNumber` of `1` instead of the actual applicable sequence number. In case segment/content is available, in contrast a correct sequence number is used and the requirement of a strictly monotonic increasing sequence number is satisfied.

In the end the reason is that the [EBUTT3Splicer](https://github.com/ebu/ebu-tt-live-toolkit/blob/master/ebu_tt_live/documents/ebutt3.py#L1003) is provided with the current sequence number the [Resequencer](https://github.com/ebu/ebu-tt-live-toolkit/blob/master/ebu_tt_live/node/consumer.py#L68) stores (and increments, when an output document is issued) - while [create_compatible_document](https://github.com/ebu/ebu-tt-live-toolkit/blob/master/ebu_tt_live/documents/ebutt3.py#L997) relies on the sequence number stored internally by [EBUTT3DocumentSequence](https://github.com/ebu/ebu-tt-live-toolkit/blob/master/ebu_tt_live/documents/ebutt3.py#L572).

**Comment by nigelmegitt** [comment]
I've been looking at #509 and the comments on it and I'm now somewhat confused about what the issue actually is.

The current behaviour is:
* Until any documents have been received, then call `create_compatible_document` which always makes an empty document with a sequence number of 1. Since this is the same document every time, and the receiving node can discard duplicates, this causes no problem.
* As soon as any documents have been received, `not document_segments` evaluates to `False` and  `EBUTT3Splicer` is called, which uses an incrementing sequence number. Even if the splicer extracts an empty document, it should still use a correctly incrementing sequence number.

Also, in relation to:

> the requirement of a strictly monotonic increasing sequence number

There is no such requirement. Sequence numbers have to increase, but not necessarily monotonically.

So now I'm wondering what test scenario results in unexpected empty documents with sequence number 1, when a different number should be used? @spoeschel please could you explain a bit more about what behaviour you're seeing and exactly what the problem is?

**Comment by spoeschel** [comment]
> * Until any documents have been received, then call `create_compatible_document` which always makes an empty document with a sequence number of 1. Since this is the same document every time, and the receiving node can discard duplicates, this causes no problem.

Agreed.

> * As soon as any documents have been received, `not document_segments` evaluates to `False` and  `EBUTT3Splicer` is called, which uses an incrementing sequence number. Even if the splicer extracts an empty document, it should still use a correctly incrementing sequence number.

In case no active document is stored (`document_segments` is empty), the `EBUTT3Splicer` is *not* invoked but again `create_compatible_document` instead. It then issues an empty document with the sequence number stored within `EBUTT3DocumentSequence`. This sequence number is independent from the sequence number provided to the `extract_segment` call and starts with the value 1.

But this number only incremented on any *received* document - not on any *issued* document. So it can (and certainly will) be lower compared to the sequence numbers supplied for/used by output documents with content. Thus it may happen that sequence numbers are reused for documents with different content (i.e. empty and non-empty documents).

In the following example, every input document has content with `dur="30s"` and every (30+x) seconds, a new input document is received.

With the current code this results in the following documents (output taken from LIT's filesystem output; I added annotations for "empty" documents):

```
14:01:12.515,ReSequenced1_1.xml (empty)
14:01:14.513,ReSequenced1_1.xml (empty)
14:01:16.546,ReSequenced1_3.xml
14:01:18.541,ReSequenced1_4.xml
14:01:20.548,ReSequenced1_5.xml
14:01:22.547,ReSequenced1_6.xml
14:01:24.548,ReSequenced1_7.xml
14:01:26.547,ReSequenced1_8.xml
14:01:28.548,ReSequenced1_9.xml
14:01:30.544,ReSequenced1_10.xml
14:01:32.547,ReSequenced1_11.xml
14:01:34.547,ReSequenced1_12.xml
14:01:36.551,ReSequenced1_13.xml
14:01:38.548,ReSequenced1_14.xml
14:01:40.548,ReSequenced1_15.xml
14:01:42.548,ReSequenced1_16.xml
14:01:44.547,ReSequenced1_17.xml
14:01:46.548,ReSequenced1_18.xml
14:01:48.515,ReSequenced1_1.xml (empty)
14:01:50.521,ReSequenced1_1.xml (empty)
14:01:52.521,ReSequenced1_1.xml (empty)
14:01:54.521,ReSequenced1_1.xml (empty)
14:01:56.521,ReSequenced1_1.xml (empty)
14:01:58.521,ReSequenced1_1.xml (empty)
14:02:00.521,ReSequenced1_1.xml (empty)
14:02:02.520,ReSequenced1_1.xml (empty)
14:02:04.519,ReSequenced1_1.xml (empty)
14:02:06.521,ReSequenced1_1.xml (empty)
14:02:08.522,ReSequenced1_1.xml (empty)
14:02:10.520,ReSequenced1_1.xml (empty)
14:02:12.520,ReSequenced1_1.xml (empty)
14:02:14.520,ReSequenced1_1.xml (empty)
14:02:16.521,ReSequenced1_2.xml (empty)
14:02:18.521,ReSequenced1_2.xml (empty)
14:02:20.545,ReSequenced1_35.xml
14:02:22.547,ReSequenced1_36.xml
14:02:24.542,ReSequenced1_37.xml
14:02:26.549,ReSequenced1_38.xml
14:02:28.578,ReSequenced1_39.xml
14:02:30.545,ReSequenced1_40.xml
14:02:32.547,ReSequenced1_41.xml
14:02:34.546,ReSequenced1_42.xml
14:02:36.548,ReSequenced1_43.xml
14:02:38.549,ReSequenced1_44.xml
14:02:40.545,ReSequenced1_45.xml
14:02:42.546,ReSequenced1_46.xml
14:02:44.546,ReSequenced1_47.xml
14:02:46.549,ReSequenced1_48.xml
14:02:48.547,ReSequenced1_49.xml
14:02:50.549,ReSequenced1_50.xml
14:02:52.521,ReSequenced1_2.xml (empty)
14:02:54.517,ReSequenced1_2.xml (empty)
14:02:56.520,ReSequenced1_2.xml (empty)
14:02:58.517,ReSequenced1_2.xml (empty)
14:03:00.521,ReSequenced1_3.xml (empty, but number reused!)
14:03:02.520,ReSequenced1_3.xml (empty, but number reused!)
14:03:04.547,ReSequenced1_57.xml
14:03:06.545,ReSequenced1_58.xml
14:03:08.547,ReSequenced1_59.xml
14:03:10.545,ReSequenced1_60.xml
```

Note that e.g. `14:02:16.521,ReSequenced1_2.xml` (i.e. empty document with an updated sequence number) is caused by the received input document, [whose sequence number overwrites the current value](https://github.com/ebu/ebu-tt-live-toolkit/blob/release/2.1.2/ebu_tt_live/documents/ebutt3.py#L917).

So sequence numbers are reused for documents with different content, which is forbidden.



The present MR leads to the following sequence of numbers:

```
14:04:23.466,ReSequenced1_1.xml (empty)
14:04:25.466,ReSequenced1_2.xml (empty)
14:04:27.493,ReSequenced1_3.xml
14:04:29.494,ReSequenced1_4.xml
14:04:31.498,ReSequenced1_5.xml
14:04:33.496,ReSequenced1_6.xml
14:04:35.497,ReSequenced1_7.xml
14:04:37.496,ReSequenced1_8.xml
14:04:39.494,ReSequenced1_9.xml
14:04:41.495,ReSequenced1_10.xml
14:04:43.494,ReSequenced1_11.xml
14:04:45.494,ReSequenced1_12.xml
14:04:47.495,ReSequenced1_13.xml
14:04:49.492,ReSequenced1_14.xml
14:04:51.495,ReSequenced1_15.xml
14:04:53.492,ReSequenced1_16.xml
14:04:55.495,ReSequenced1_17.xml
14:04:57.493,ReSequenced1_18.xml
14:04:59.469,ReSequenced1_19.xml (empty)
14:05:01.464,ReSequenced1_20.xml (empty)
14:05:03.463,ReSequenced1_21.xml (empty)
14:05:05.463,ReSequenced1_22.xml (empty)
14:05:07.469,ReSequenced1_23.xml (empty)
14:05:09.466,ReSequenced1_24.xml (empty)
14:05:11.494,ReSequenced1_25.xml
14:05:13.493,ReSequenced1_26.xml
14:05:15.495,ReSequenced1_27.xml
14:05:17.493,ReSequenced1_28.xml
14:05:19.495,ReSequenced1_29.xml
14:05:21.496,ReSequenced1_30.xml
...
```

In the end, for every new issued document, the sequence number is increased. A disadvantage is that the sequence number actually also increases when the empty document is repeated. If that is intended behaviour that shall be kept, one could in theory remove that mentioned sequence number overwrite......maybe this would automatically fix this very issue as well.........

**Comment by nigelmegitt** [comment]
> If that is intended behaviour that shall be kept, one could in theory remove that mentioned sequence number overwrite......maybe this would automatically fix this very issue as well.

That is intended behaviour, but I'm not sure exactly what you're suggesting, though it does sound very interesting!

**Comment by spoeschel** [comment]
I played again around a bit and rethought things: It seems that all this is rather a more general question/issue with the generated sequence numbers here:

The sequence number of an empty document (generated by `create_compatible_document`) is independent from the sequence number of a document with content (generated by the `EBUTT3Splicer`).

The former sequence number is stored in `EBUTT3DocumentSequence`. It is (at least for the case of the Resequencer) not increased after each empty document is emitted. [However it is updated when the sequence number of an input document is higher than the currently stored number](https://github.com/ebu/ebu-tt-live-toolkit/blob/release/2.1.2/ebu_tt_live/documents/ebutt3.py#L917). As the initial number is 0, it is definitely updated by the first input document....and also by subsequent input documents.

The later sequence number is stored in `ReSequencer` itself as `_segment_counter` and starts with 1. It is incremented after *any* document (with or without content) has been emitted, and has no relation to the input document's sequence numbers.

Consider the (extreme) case that the first input document has the sequence number 5000. In this case, the following sequence of documents (and their corresponding sequence numbers) can occur:

```
14:01:12.515,ReSequenced1_5000.xml (empty)
14:01:14.513,ReSequenced1_5000.xml (empty)
14:01:16.546,ReSequenced1_3.xml
14:01:18.541,ReSequenced1_4.xml
14:01:20.548,ReSequenced1_5.xml
14:01:22.547,ReSequenced1_6.xml
14:01:24.548,ReSequenced1_7.xml
14:01:26.547,ReSequenced1_8.xml
14:01:28.548,ReSequenced1_9.xml
14:01:30.544,ReSequenced1_10.xml
14:01:32.547,ReSequenced1_11.xml
14:01:34.547,ReSequenced1_12.xml
14:01:36.551,ReSequenced1_13.xml
14:01:38.548,ReSequenced1_14.xml
14:01:40.548,ReSequenced1_15.xml
14:01:42.548,ReSequenced1_16.xml
14:01:44.547,ReSequenced1_17.xml
14:01:46.548,ReSequenced1_18.xml
14:01:48.515,ReSequenced1_5000.xml (empty)
14:01:50.521,ReSequenced1_5000.xml (empty)
14:01:52.521,ReSequenced1_5000.xml (empty)
14:01:54.521,ReSequenced1_5000.xml (empty)
...
```

...which looks odd - for me it is a bit weird that the sequence numbers of the input documents only affect one of the two possible types of documents (with or without content).

So the question arises....how should a proper output of the sequencer number be? Should the empty document always have the same sequence number? Should this only affect adjacent emissions (i.e. repetitions)? Or also any later emission (so that the empty document always had the same sequence number e.g. 1)? Should the emitted sequence numbers in general start at 1 or at the number the first input document has? I wonder about the reason for the mention sequence number updating based on the input document...

**Comment by nigelmegitt** [comment]
Thanks for this analysis @spoeschel . It's clear to me that the output sequence numbers should not depend on the input sequence numbers, since they're independent sequences. If a document is being repeated the same sequence number can be used but does not have to be used. It is less work downstream if the same sequence number is used and the document can be discarded early, but that is the only advantage.

There is also a potential requirement to generate sequence numbers using some algorithmic mechanism, as discussed out of band.

My conclusion here is that we should probably merge #509 for release/2.1.2 as a temporary fix but open an issue to rework this code in a future release. 

My suggested implementatino approach would be to be able to pass into the document generating code a sequence number generating object that provides an interface, where different instantiations of that object can create sequence numbers using different strategies and starting numbers. For example, one could begin at 1 and go up, and another could use a number based on the current time.

The sequence number generator would be instantiated at runtime based on configuration. Would that work for you @spoeschel ? I'm not sure if/when I will be able to implement it and would welcome that implementation as a contribution, as always.

**Comment by spoeschel** [comment]
> Thanks for this analysis @spoeschel . It's clear to me that the output sequence numbers should not depend on the input sequence numbers, since they're independent sequences. If a document is being repeated the same sequence number can be used but does not have to be used. It is less work downstream if the same sequence number is used and the document can be discarded early, but that is the only advantage.

This MR removes that sequence number repetition for now, but I think it is reasonable (until a final solution) to first fix the general issue of "inconsistent" numbering, by merging this MR.

> My conclusion here is that we should probably merge #509 for release/2.1.2 as a temporary fix but open an issue to rework this code in a future release.

Agreed.

> My suggested implementatino approach would be to be able to pass into the document generating code a sequence number generating object that provides an interface, where different instantiations of that object can create sequence numbers using different strategies and starting numbers. For example, one could begin at 1 and go up, and another could use a number based on the current time.
> 
> The sequence number generator would be instantiated at runtime based on configuration. Would that work for you @spoeschel ? I'm not sure if/when I will be able to implement it and would welcome that implementation as a contribution, as always.

This sounds good to me. It would also allow to test other implementations e.g. by providing a generator that always returns the same sequence number, despite the actual subtitles content.

**Comment by nigelmegitt** [comment]
OK I will go ahead with this.
