### ISSUE TITLE
Resequencer: allow to immediately issue documents

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-live-toolkit#505]
So far the resequencer starts to regularly issue documents only after the first EBU-TT Live document has been received. However for some use cases this might be inconvenient as an active document must exist at all times e.g. when creating segments for an MPEG-DASH stream. The reason for documents being issued only after the first received EBU-TT Live document is that certain parameters of that document are used for initialisation.

**Comment by nigelmegitt** [comment]
Yes, this is true. I guess perhaps some kind of init document could be processed to initialise the resequencer.

**Comment by spoeschel** [comment]
I think this is the most elegant and future-proof way to address this; I will prepare a MR...

**Comment by nigelmegitt** [comment]
Many thanks!
