### ISSUE TITLE
Create text equivalent list of normative spec requirements

### ISSUE THREAD

**Issue by nigelmegitt** [ebu/ebu-tt-live-toolkit#51]
Generate a text format list of the normative spec requirements against which we can write tests.

**Comment by nigelmegitt** [comment]
This will help with #45.

**Comment by nigelmegitt** [comment]
Working on this at https://github.com/ebu/ebu-tt-live-toolkit/blob/issue-51-conformance-requirements/testing/SPEC-CONFORMANCE.md if anyone wants to take an early look.

**Comment by frans-ebu** [comment]
One thing I wondered is if we want to add the origin of the requirement. E.g. in an additional column?
Now all are from Tech 3350, but as you said, there may be others from related specs (Part 1, TTML1SE, etc.).

**Comment by nigelmegitt** [comment]
Good idea!
