### ISSUE TITLE
EBUTT3DocumentSequence: format ERR_DOCUMENT_NOT_COMPATIBLE strings

### ISSUE THREAD

**Issue by spoeschel** [ebu/ebu-tt-live-toolkit#514]
In `EBUTT3DocumentSequence` the `ERR_DOCUMENT_NOT_COMPATIBLE` is used without specifying the actually affected attribute names [[1]](https://github.com/ebu/ebu-tt-live-toolkit/blob/release/2.1.2/ebu_tt_live/documents/ebutt3.py#L645) [[2]](https://github.com/ebu/ebu-tt-live-toolkit/blob/release/2.1.2/ebu_tt_live/documents/ebutt3.py#L650).

**Comment by nigelmegitt** [comment]
Thanks for raising this @spoeschel ; to add an extra piece of information, the definition string of `ERR_DOCUMENT_NOT_COMPATIBLE` includes a template variable for the attribute names, so it makes sense to use it.
