### ISSUE TITLE
Differentiate empty and missing template variable

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#56]
For example, if : ```test_var = "?None?"``` and we have template :

```
{% if test_var != "?None?" %}
    <a_tag>{{ test_var }}</a_tag>
{% endif % }
```

So if ```test_var = '' ``` the tag will be present but will contain an empty string.

**Comment by gilbrechbuhler** [comment]
This was the base idea, but I thought about it and I wonder if it would not be more logical to have "?Empty?" for example, meaning that when the variable contains '' the element does not appear at all, and when it contains "?Empty?" it appears but with an empty value.

The logic behind this is that the case where want to have an attribute present but empty for some tests will be more rare than the case where we just don't want the element if it is empty.

**Comment by gilbrechbuhler** [comment]
Actually it seems that the first solution is more intuitive in general.

**Comment by gilbrechbuhler** [comment]
Here I have a little problem with that file https://github.com/ebu/ebu-tt-live-toolkit/blob/master/testing/bdd/features/validation/timeBase_timeformat_constraints.feature .

So when testing body attribute I do not specify values for p_begin or p_end for example, otherwise the example arraw becomes big and quite unreadable. But Jinja2 defaults  variable to an empty string. Meaning that if for example p_begin has not been set but is accessed in the template, its value will be '', the empty string. Moreover when you do ```{% if var %}``` in Jinja2 it does not enter the if statement if the variable is equal to the empty string (which is the expected behavior). What happens is that the unspecified values are equal to '' and not "*?None?*" and thus appear but are empty which makes the validation fail.

Going back to our problem, this means that we cannot use the first solution proposed in this issue easily.

**Comment by frans-ebu** [comment]
Just to note that the latest commits implement the second solution: 

When the variable contains '' the element does not appear at all, and when it contains "?Empty?" it appears but with an empty value.

I think that is fine, (as @gilbrechbuhler answered it is in line with the Ninja2 default).

**Comment by nigelmegitt** [comment]
PR merged; closing.
