### ISSUE TITLE
markerMode continuous ?

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#61]
From what I understand from https://git.ebu.io/ebutt/ebutt-part-3/issues/115 , markerMode="continuous" is permitted with timeBase="smpte", however this is not allowed by the spec and the schema definitions. Should it be added in the xsd files so we have at least semantically correct smpte cases ? (here for example : https://github.com/ebu/ebu-tt-live-toolkit/blob/a7a545d189e4a12d6c8632929fd019252de2e4cb/testing/bdd/templates/referenceClockIdentifier.xml )

**Comment by nigelmegitt** [comment]
Yes, I believe it should be added, as discussed in gitlab [issue 114](https://git.ebu.io/ebutt/ebutt-part-3/issues/114) and [issue 115](https://git.ebu.io/ebutt/ebutt-part-3/issues/115).

**Comment by gilbrechbuhler** [comment]
I add it in the xsd file then.

**Comment by nigelmegitt** [comment]
I think we need to include the fix for time expression mapping to timeDelta in #62 as well as the XSD and the tests.

**Comment by nigelmegitt** [comment]
Here's a useful reference from TTML1: https://www.w3.org/TR/ttml1/#time-expression-semantics-smpte

**Comment by gilbrechbuhler** [comment]
Fixed by #62 that was merged. We can close this one.
