### ISSUE TITLE
Document manifest format

### ISSUE THREAD

**Issue by frans-ebu** [ebu/ebu-tt-live-toolkit#64]
We need to document the manitfest format. E.g.

- [x] in the code
- [ ] in the wiki
- [ ] in the header of the manifest file?

related to: https://github.com/ebu/ebu-tt-live-toolkit/pull/59

**Comment by frans-ebu** [comment]
Ideas we may want to include:

- manifest file says when documents become available
- timeline used same as in documents
- writing (thus reading) order is top down; every time a new document becomes available a row is added (but time may loop, depends on time type)

**Comment by nigelmegitt** [comment]
I wouldn't bother documenting in any detail in the manifest file, but maybe include some kind of custom header line.

+1 to all those ideas to include!

**Comment by frans-ebu** [comment]
Should we reference the github wiki from that header line?

**Comment by gilbrechbuhler** [comment]
I can write it, the remaining question being : where do we want this documentation ? Readme ? Wiki ? I can even write it and we decide where we put it after.

**Comment by nigelmegitt** [comment]
Depends a bit on how long it is. I would quite like to see it in the auto-generated code documentation, and also would be happy with (additionally) a note in the wiki, which could be a bit longer if that would be helpful, and we could use that placeholder to explain why the file system carriage mechanism is useful at all.

**Comment by gilbrechbuhler** [comment]
Ok, for me if we want it in the auto-generated code documentation, the most logical place is in the documentation concerning the FilesystemProducerImpl as it the one who creates the manifest in the first place, do you agree ?

**Comment by nigelmegitt** [comment]
I agree!

**Comment by frans-ebu** [comment]
Yep!

**Comment by nigelmegitt** [comment]
Manifest format documented only in code so far.

**Comment by kozmaz87** [comment]
What is our status on this right now?

**Comment by nigelmegitt** [comment]
Need to add a .rst file or something similar to describe the manifest format in the documentation of filesystem carriage mech.

**Comment by gilbrechbuhler** [comment]
It is actually documented here : http://ebu.github.io/ebu-tt-live-toolkit/html/ebu_tt_live.carriage.html#module-ebu_tt_live.carriage.filesystem

The documentation in the code is generated there. If you want I can add a .rst file to write this in a more visible place as well, like I did for the user input producer ?

**Comment by nigelmegitt** [comment]
Yes please add it in a more visible place, and also include the syntax of the two elements per line in the file format in that documentation. (I know it's v simple!).
