### ISSUE TITLE
Timeformats in documents

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#66]
Time formats in documents are a bit confusing :

`<tt:body tt:begin="63016289ms" tt:dur="00:00:01">`

Can we chose the format used to convert timedeltas more precisely ? For example here, having begin in hh:mm:ss.ms and dur in xxxxxms format would be more logical.

Raised from discussion during 13/07/2016 call.

**Comment by frans-ebu** [comment]
Or even use the same format for both. As @nigelmegitt noted the spec allows for mixing, but some combinations are more intuitive than others. The current one is not very intuitive I'd say :)

**Comment by kozmaz87** [comment]
Is there any plan on restricting the spec about this? To only allow the more intuitive ones.

**Comment by nigelmegitt** [comment]
No, the spec won't change. This is just a matter of what we do by default in the interop toolkit, and what we allow to be configured.

**Comment by EyalLavi** [comment]
@kozmaz87 before we close this can you please confirm that all combinations are supported?

**Comment by nigelmegitt** [comment]
Friendly reminder to @kozmaz87 that there's an outstanding question for him here.

**Comment by kozmaz87** [comment]
what wait what? do you want me to test with all kinds? I mean one can write bdd for this and try them in... what do you need me to do on this?

**Comment by EyalLavi** [comment]
I just wanted to confirm before closing the ticket that those exotic time expression combinations have been taken into account. In the feature files for timings we use mainly e.g. `00:00:00.000` and `1s`.

**Comment by kozmaz87** [comment]
yes. well exotics are unfortunately valid. That is the spec. There is nothing i could do about them.

**Comment by nigelmegitt** [comment]
Translation: yes they are taken into account. They're in the XSD and processed by the bindings generator.

**Comment by EyalLavi** [comment]
Thank you for the reassurance. This can be closed now.

**Comment by kozmaz87** [comment]
Yaaay happiness overload.... there may have been too much friday treatment for me.
