### ISSUE TITLE
Create time metric tests (for smpte)

### ISSUE THREAD

**Issue by nigelmegitt** [ebu/ebu-tt-live-toolkit#69]
See #67 and #68: issue is to create tests that verify that the correct time units are used and the code does not get `ms` and `m` confused with each other.

**Comment by gilbrechbuhler** [comment]
I don't close this one finally because we miss the checks for smpte, but as conversion from smpte is not implemented yet at all, it will have to wait.

Waits on #70

**Comment by nigelmegitt** [comment]
SMPTE time expressions are no longer required. Closing.
