### ISSUE TITLE
Timedelta <-> SMPTE conversion

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#70]
Conversion  between XML time formats and timedelta values is done in [this file](https://github.com/ebu/ebu-tt-live-toolkit/blob/master/ebu_tt_live/bindings/_ebuttdt.py). This setup allows us to do the conversions during pyxb binding loop.

Conversion for SMPTE is a bit more complicated than conversion for clock and media times. Indeed for SMPTE we need to access values of some attributes of the `<tt>` element, which is not easily done through pyxb at the stage of the binding where the conversion happens.

**Comment by nigelmegitt** [comment]
Just for clarity, #62 does not resolve this issue but gives rise to it.

**Comment by nigelmegitt** [comment]
SMPTE time expressions are no longer required. Closing.
