### ISSUE TITLE
No dur attribute if ttp:markerModer="discontinuous"

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#71]
`tt:dur` is not allowed when a document has both `ttp:timeBase="smpte"` and `ttp:markerMode="discontinuous"`

**Comment by nigelmegitt** [comment]
Just for clarity, #62 does _not_ resolve this issue but gives rise to it.

**Comment by kozmaz87** [comment]
I think this should be closed as we aren't doing discontinuous

**Comment by nigelmegitt** [comment]
EBU group has agreed to remove discontinuous marker mode, so closing.
