### ISSUE TITLE
live semantic validation

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#73]
using the framework created in #72 write the semantic rules in code according to normative rules.
- [x] Create a set of sub-tasks based on the [SPEC-CONFORMANCE.md](https://github.com/ebu/ebu-tt-live-toolkit/blob/master/testing/SPEC-CONFORMANCE.md) document
  - [x] timeBase, frameRate, clockMode, dropMode, frameRateMultiplier semantic rules R11
  - [x] documentMetadata ordering of children as described in 3.2.2.2(R38,R39)
  - [x] timing type constraints based on timeBase R45-R65
  - [x] Exactly one or zero documents active at each moment in time R1, R13, R14
  - [x] A document shall be associated with exactly one sequence R5
  - [x] Sequence identifier present R6, R34
  - [x] Sequence number present R7, R36
  - [x] Documents with sequence id and  number already seen shall be discarded R107 #297
  - [x] Resolved begin and end times R15
  - [x] Resolved begin time R16
  - [x] Resolved end time R17

**Comment by nigelmegitt** [comment]
@kozmaz87 I've updated the list of semantic rules that apply to sequences, above. There are more rules that apply per-document that may not already be captured by the existing bindings validation.

**Comment by nigelmegitt** [comment]
Just ticked R16 and R17 because they're showing in spec conformance as having tests - please undo if that's not the case.

**Comment by nigelmegitt** [comment]
Moving incomplete parts to #342 for post-R2.

**Comment by nigelmegitt** [comment]
I think R1, R13, R14 and R15 are actually done now, possibly awaiting a PR merge. @kozmaz87 @EyalLavi are you able to confirm?
