### ISSUE TITLE
Reference R numbers from SPEC-CONFORMANCE document in tests

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#75]

**Comment by nigelmegitt** [comment]
Has #74 fully addressed this issue?

**Comment by gilbrechbuhler** [comment]
For the tests currently in master branch yes. And in any new PR I both complete the SPEC-CONFORMANCE file and add references to it in the tests. So it is completely handled I think.

**Comment by nigelmegitt** [comment]
Thanks, closing.
