### ISSUE TITLE
Create a "stoppedClock" (or similar name) clock

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#80]
We need a clock on which we can do : `clock.set_time(time)` that will always return `time` if we do `clock.get_time()` unless we change `time` with another call to `set_time`

**Comment by nigelmegitt** [comment]
This would support something like:

As a _tester_ I want a node to process a sequence with pre-defined per-document availability times so that the test output is consistent regardless of when the test is run.

**Comment by kozmaz87** [comment]
get_time() function should be overwritten in this case to serve the saved value... unless there is some crazy usecase which requires the normal functionality along with the stopped clock functionality at the same time....
