### ISSUE TITLE
py.test is not callable

### ISSUE THREAD

**Issue by frans-ebu** [ebu/ebu-tt-live-toolkit#9]
`py.test` is not callable, but [CONTRIBUTING.md](CONTRIBUTING.md) says it is

**Comment by kozmaz87** [comment]
wait... make test was a TODO item
expecially because I have to reinvent the wheel in the windows version. py.test doesn't run for Nigel either... I am unsure why...

**Comment by frans-ebu** [comment]
Fair, I should not have mixed the two issues - removed the ref to the make part.

**Comment by kozmaz87** [comment]
This seems to be an issue with how setuptools handles test_requires. The packages don't get installed into the virtual environment instead they get put in the ignored .eggs folder. This way setup.py can use them but py.test will not work from command line unless those packages are installed into the virtual environment.

**Comment by kozmaz87** [comment]
commit 090745c should fix this

**Comment by frans-ebu** [comment]
@kozmaz87 great, it works indeed.
