### ISSUE TITLE
Log semantic validation

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#92]
For each part 3 document received, log successful semantic validation, or if unsuccessful, what errors encountered. This is a subtask of the simple consumer. See #87

**Comment by nigelmegitt** [comment]
I would like to see a positive log message describing the document that has been received, i.e. sequence number, availability time, validation status.

**Comment by kozmaz87** [comment]
So far on the logging front these are the messages:

  DOC_SYNTACTIC_VALIDATION_SUCCESSFUL = gettext('Syntactic validation successful')
  DOC_SEMANTIC_VALIDATION_SUCCESSFUL = gettext('Semantic validation successful')
  DOC_DISCARDED = gettext('Document {sequence_identifier}__{sequence_number} is discarded')
  DOC_TRIMMED = gettext('Document {sequence_identifier}__{sequence_number} activation change: [{resolved_begin_time}; {resolved_end_time}]')

**Comment by nigelmegitt** [comment]
Seems like a reasonable set. Do you put out the last message first time a document arrives as well as when it's activation times change?

**Comment by kozmaz87** [comment]
No. This is only due to sequencing resulting in trimming. If the document is successfully inserted there is no log currently... Assuming from our approach that you would like me to have something similar on successful insertion as well..

**Comment by nigelmegitt** [comment]
Yes please!
