### ISSUE TITLE
User Input Producer : develop a Carriage Implementation able to parse the data sent from the UI by the user

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#99]
Task for #20 
At the end of this task the goal is to have a carriage implementation that gets the data sent by the UI and gives them correctly to the node. The HTTP server would be implemented here.

**Comment by nigelmegitt** [comment]
See #101 - this may turn into no task if the UI simply generates documents and sends them over say WebSocket to a transfer node.

**Comment by gilbrechbuhler** [comment]
Closing because we use another method (websockets) finally.
